In [25]:
import numpy as np

In [43]:
edades = np.random.uniform(
    low= 20,
    high= 50,
    size= (3,3)
)
matriz_edades = np.round(edades)
matriz_edades

array([[29., 49., 29.],
       [38., 37., 50.],
       [49., 25., 47.]])

In [44]:
ingresos = np.random.uniform(
    low= 2000,
    high= 5000,
    size= (3,3)
)
matriz_ingresos = np.round(ingresos)
matriz_ingresos

array([[4732., 3190., 4768.],
       [4445., 2567., 2065.],
       [4347., 4737., 3947.]])

In [45]:
array_edades = matriz_edades.reshape(9,1)
array_ingresos = matriz_ingresos.reshape(9,1)
edades_ingresos = np.column_stack((array_edades, array_ingresos))
display(
    array_edades,
    array_ingresos,
    edades_ingresos
)

array([[29.],
       [49.],
       [29.],
       [38.],
       [37.],
       [50.],
       [49.],
       [25.],
       [47.]])

array([[4732.],
       [3190.],
       [4768.],
       [4445.],
       [2567.],
       [2065.],
       [4347.],
       [4737.],
       [3947.]])

array([[  29., 4732.],
       [  49., 3190.],
       [  29., 4768.],
       [  38., 4445.],
       [  37., 2567.],
       [  50., 2065.],
       [  49., 4347.],
       [  25., 4737.],
       [  47., 3947.]])

In [46]:
bool_edades = np.logical_and(array_edades > 20, array_edades < 30)
bool_inger = np.logical_and(array_ingresos > 2000, array_ingresos < 5000)
bool_matr = np.column_stack((bool_edades, bool_inger))
display (
    bool_edades,
    bool_inger,
    bool_matr
)

array([[ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False]])

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

array([[ True,  True],
       [False,  True],
       [ True,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [ True,  True],
       [False,  True]])

In [47]:
validaCumple = np.logical_and(bool_edades, bool_inger)
validaCumpleColum = np.column_stack((validaCumple, validaCumple))
validaCumpleColum


array([[ True,  True],
       [False, False],
       [ True,  True],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True,  True],
       [False, False]])

In [48]:
print("Los registros que cumple las condiciones son: ")
edades_ingresos[validaCumpleColum]

Los registros que cumple las condiciones son: 


array([  29., 4732.,   29., 4768.,   25., 4737.])